# SPDX-License-Identifier: MIT

# 鼠标模拟
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# 电源管理
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_PM_SOFT_OFF=y

# HID（macOS 兼容）
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# 蓝牙
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 分体电池上报
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# 设置存储防抖（ms）
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=60000
